### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)+ Windows

### ISSUE THREAD

**Issue by RameshPonnusami** [stefanondisponibile/flask_celery#1]
Solution:
celery -A celery_worker.celery worker --pool=solo -l info

**Comment by stefanondisponibile** [comment]
Thank you @RameshPonnusami. May I ask if you're experiencing this issue when running on Windows?

**Comment by RameshPonnusami** [comment]
> Thank you @RameshPonnusami. May I ask if you're experiencing this issue when running on Windows?

yes, This command is workaround
ref: https://github.com/celery/celery/issues/4178

**Comment by RameshPonnusami** [comment]
Thanks buddy, Its actually great and I can easily understand with the medium blog and with your code as well.

**Comment by stefanondisponibile** [comment]
Perfect, I had alread referenced this [here](https://medium.com/@frassetto.stefano/im-sorry-but-i-m-not-able-to-reproduce-that-as-i-don-t-have-any-windows-pc-available-at-the-f2a977d68850) in the medium blog post as another user was experiencing the same issue. I'll soon update the post with a reference to this.

**Comment by RameshPonnusami** [comment]
> Perfect, I had alread referenced this [here](https://medium.com/@frassetto.stefano/im-sorry-but-i-m-not-able-to-reproduce-that-as-i-don-t-have-any-windows-pc-available-at-the-f2a977d68850) in the medium blog post as another user was experiencing the same issue. I'll soon update the post with a reference to this.

Sure bro
